modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"

[[mods]]
modId="fromspores"
version="1.0.4"
displayName="From Spores"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="fromspores.png"
credits="Me"
authors="Arcegy"
description='''
A mod that adds a new mob, new effect and a new weapon themed around the spores on warped fungus.
'''
